### ISSUE TITLE
到处

### ISSUE THREAD

**Issue by airflow0qm** [hk4170/sudata#6]
倒出数据库导出csv时有错误

**Comment by hk4170** [comment]
回复测试




GAVIN
***@***.***




------------------ 原始邮件 ------------------
发件人: airflow0qm ***@***.***&gt;
发送时间: 2023年6月1日 15:43
收件人: hk4170/sudata ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [hk4170/sudata] 到处 (Issue #6)





 
倒出数据库导出csv时有错误
